services:
  postgres:
    image:
      postgres: 13
      conatainer_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka:latest
    conatainer_name: kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "21811:21811"
  
  user_service:
    build: ./user
    ports:
      -"8001:8001"
    depends_on:
      - postgres
      -  kafka

  product_service:
    build: ./product
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - kafka
  
  purchase_service:
    build: ./purchase
    ports:
      - "8003:8003"
    depends_on:
      - postgres
      - kafka

  cart_service:
    build: ./cart
    ports:
      - "8004:8004"
    depends_on:
      - postgres
      - kafka


